import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
config :seshat, SeshatWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # Development-only Phoenix signing secret, not an API key or production
  # credential. Production reads its own SECRET_KEY_BASE from the environment.
  secret_key_base: "WzEnBLTXYTO4PyC89N3vNsrLR7m8zEBlKka44zBFWYEFC1PqJgw1co9TbzbPskR7"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Mirror the dev log to a file, *in addition* to the terminal — the default
# handler is untouched, so the `iex -S mix phx.server` session still prints
# everything it always did.
#
# This exists for the smoke tests. Several checks in
# docs/smoke_tests/auto/mirror.md are read out of the server log rather than out of
# state, because a debounced refresh that ran and one that didn't leave an
# identical mirror — only the `Song:` / `Loaded N tracks:` lines distinguish
# them. With console-only logging those tests could be run by a human reading
# the server's terminal and by nobody else. A file the agent sweep can open is
# what keeps them zero-user.
#
# Timestamps are kept here even though the console format drops them: the
# burst-coalescing tests compare tool-call times against refresh times, so a
# line without one is useless to them.
#
# Anchored to __DIR__ for the same reason as :catalog_path below — `mix mcp` is
# launched by the MCP client, whose cwd is not ours, and a relative path would
# scatter log files wherever that happens to be.
config :seshat, :logger, [
  {:handler, :file_log, :logger_std_h,
   %{
     config: %{
       file: ~c"#{Path.expand("../log/dev.log", __DIR__)}",
       # Small, so a test reading the tail sees the last line promptly rather
       # than waiting on the default multi-second flush.
       filesync_repeat_interval: 500,
       # Rotation, so this can never grow without bound: 10MB per file and 3
       # archives is a ~40MB ceiling that no smoke run comes close to. Without
       # max_no_files the handler truncates instead of rotating, which would
       # invalidate a byte offset a test had already taken.
       max_no_bytes: 10_000_000,
       max_no_files: 3
     },
     formatter: Logger.Formatter.new(format: "$time [$level] $message\n")
   }}
]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Keep the sound catalog in the project root in dev so it can be inspected by
# eye. Gitignored — it's machine-specific. Installed builds keep the default
# (~/.seshat/catalog.json). Anchored to __DIR__ rather than left relative
# because `mix mcp` is launched by the MCP client, whose cwd is not ours.
config :seshat, :catalog_path, Path.expand("../catalog.json", __DIR__)

# ...and indent it, for the same reason. Installed builds stay minified: the
# file is 1.45x the size pretty-printed, which buys nothing where no one reads it.
config :seshat, :catalog_pretty, true

# Load local secrets if present (never committed)
if File.exists?("config/dev.secret.exs"), do: import_config("dev.secret.exs")
