defmodule Seshat.MCP.Server do
  @moduledoc """
  MCP server exposing Ableton Live control tools.

  Clients (e.g. Claude Desktop, Claude Code) connect over stdio (`mix mcp`) or
  streamable HTTP (started with the app) and can discover and call every tool
  in `Seshat.Tools.Definitions`.

  Components are generated by `Seshat.MCP.Tools` rather than listed here, so
  this server can't drift from the tool definitions.

  Session-level guidance — the conventions no single tool description can
  carry — is sent as server `instructions` from `Seshat.Instructions`, shared
  with API-key mode's system prompt.
  """

  use Anubis.Server,
    name: "seshat",
    version: "0.1.0",
    capabilities: [:tools]

  # Forces Seshat.MCP.Tools — and the components it generates — to compile first.
  require Seshat.MCP.Tools

  # Resolved at session init rather than compile time, so editing the text is a
  # one-file change in Seshat.Instructions. A module-defined callback wins over
  # the `use`-option default: Anubis checks Module.defines?/2 before injecting
  # its own. Returning nil omits the field from the initialize result entirely.
  @impl Anubis.Server
  def server_instructions, do: Seshat.Instructions.text()

  for module <- Seshat.MCP.Tools.all() do
    component(module)
  end
end
