defmodule Seshat.MCP.Server do
  @moduledoc """
  MCP server exposing Ableton Live control tools.

  Clients (e.g. Claude Desktop, Claude Code) connect over stdio (`mix mcp`) or
  streamable HTTP (started with the app) and can discover and call every tool
  in `Seshat.Tools.Definitions`.

  Components are generated by `Seshat.MCP.Tools` rather than listed here, so
  this server can't drift from the tool definitions.
  """

  use Anubis.Server,
    name: "seshat",
    version: "0.1.0",
    capabilities: [:tools]

  # Forces Seshat.MCP.Tools — and the components it generates — to compile first.
  require Seshat.MCP.Tools

  for module <- Seshat.MCP.Tools.all() do
    component(module)
  end
end
